// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnzgnsodowyccuyzaayx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuemduc29kb3d5Y2N1eXphYXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDk3MDMsImV4cCI6MjA2ODI4NTcwM30.ZAWCXwPIYo9lXuWGThpn6UzJORhsehkGNimK2tys8so";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});